### ISSUE TITLE
A error parameter -j2 when build with cmake?

### ISSUE THREAD

**Issue by Eipgen** [pyscf/pyscf-forge#37]
https://github.com/pyscf/pyscf-forge/blob/5e4236cf25a4b683ac053310243c929d76c2aeab/setup.py#L97

```
cmake --build build/temp.linux-x86_64-cpython-310 -j2
Unknown argument -j2
Usage: cmake --build <dir> [options] [-- [native-options]]
Options:
  <dir>          = Project binary directory to be built.
  -j [<jobs>] --parallel [<jobs>] = Build in parallel using
                   the given number of jobs. If <jobs> is omitted
                   the native build tool's default number is used.
                   The CMAKE_BUILD_PARALLEL_LEVEL environment variable
                   specifies a default parallel level when this option
                   is not given.
  --target <tgt> = Build <tgt> instead of default targets.
                   May only be specified once.
  --config <cfg> = For multi-configuration tools, choose <cfg>.
  --clean-first  = Build target 'clean' first, then build.
                   (To clean only, use --target 'clean'.)
  --use-stderr   = Ignored.  Behavior is default in CMake >= 3.0.
  --             = Pass remaining options to the native tool.
error: command '/usr/local/bin/cmake' failed with exit code 1
`

**Comment by matthew-hennefarth** [comment]
I can't seem to reproduce the problem on my end (MacOS) by calling either `setup.py build` or manually, by hand, calling 

```
cmake -Spyscf/lib -Bpyscf/lib/build
cmake --build pyscf/lib/build -j2
```

It works either way. Can you provide a bit more details about how you are invoking the `setup.py` script?

**Comment by Eipgen** [comment]
> I can't seem to reproduce the problem on my end (MacOS) by calling either `setup.py build` or manually, by hand, calling
> 
> ```
> cmake -Spyscf/lib -Bpyscf/lib/build
> cmake --build pyscf/lib/build -j2
> ```
> 
> It works either way. Can you provide a bit more details about how you are invoking the `setup.py` script?

it seems my `Cmake` in my linux is too old(v3.13.4), and when I change "`-j2`" to "`-j 2`", it build smoothly.  I have tested with newer cmake(v3.19.6),  it can build now. Thank you.
